### PR TITLE
Add vibe.js to the list of tools

### PR DESCRIPTION
**Pull request by felipenmoura**
Vibe.js allows you to create and test patterns to use the JavaScript's Vibrate API in a visual way.

### CODE REVIEW

**Comment by pepelsbey** [comment]
We're not collecting tools, we're collecting progressive web apps that make good case for developers to use this set of technologies. I don't think Vibe.js would fit this list.

**Comment by felipenmoura** [comment]
Hi...
ok, but...how come the [QRCoreScan](https://qrcodescan.in/), the [wavePad](https://alexgibson.github.io/wavepad/) and the [airHorner(!!!!!)](https://airhorner.com/) fit this description?!

I mean, [vibe.js](https://github.com/NascHQ/vibe.js) meets all the criteria, works offline, caches even the sound, is open source, works well in computers and mobile devices, has the manifest all set up, is responsive, uses service workers and works normally offline or in poor connections, can be installed.
It uses the audio api and vibrate api.

Could you please tell me what is missing? So I can change it for it to be seen as an interesting case for these technologies, then?
Maybe if I remove the logo in the corner, or something like that?

Thank you.

**Comment by pepelsbey** [comment]
@felipenmoura, none of the mentioned app are made for developers, they all serve some consumer needs: sound, music, code reading. Also desing of the app is far from that we’d feature.

**Comment by felipenmoura** [comment]
I understand, thanks @pepelsbey.

**Pull request closed without merging**
